#服务启动端口
server :  
  port :  8086

#数据库配置
spring:
    datasource:
        name: test
        url: jdbc:postgresql://192.168.1.226:5432/scm5
        username: ccccit
        password: ccccit
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      host: 192.168.2.5
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6381
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
mybatis:
  type-aliases-package: com.ccccit.spring.boot.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log
    level: 
        com.ibatis:DEBUG
        root:DEBUG

task:
    cron:0 0/5 * * * ?
villain:
  excel:
    path: C:\Users\user\Desktop\1\test.xlsx

